### ISSUE TITLE
Planning node

### ISSUE THREAD

**Issue by davidbacisin** [davidbacisin/cwru-ros-pkg-hydro-beta#11]
ROS Service which receives requests by segment_id (integer), and responds with a heading and distance (floats)

Knows the total path segments and where in the path sequence it is.

**Comment by Sandstome** [comment]
planning node (service) - knows total path segments and where in the path sequence it is
	-input- vel_scheduler queries with segment_id
	-output- segment_param to vel_scheduler

**Comment by davidbacisin** [comment]
Advertises on `path_planner_service` and uses the message format in `/path_planner/srv/path_segment.srv`
