### ISSUE TITLE
vel_scheduler planning service client

### ISSUE THREAD

**Issue by davidbacisin** [davidbacisin/cwru-ros-pkg-hydro-beta#12]
Sends segment_id (integer) to planning service to receive a heading and distance (both floats).

**Comment by Sandstome** [comment]
ros::ServiceClient client = n.serviceClient<PathPlanner::PathPlanner>("path_planner_service");
path_planner::path_segment srv;

double next_segment(int segment_current) {

srv.request.id = segment_current;
	double dist_to_go = 0.0;        
	if (client.call(srv)) {
		if (fabs(srv.response.heading) > srv.response.distance)
	dist_to_go = srv.response.heading;
		else
	dist_to_go = srv.response.distance;	

                
            }
	else
		dist_to_go = 0.0;
return dist_to_go;
}
