### ISSUE TITLE
Email Response From Luc 

### ISSUE THREAD

**Issue by Sandstome** [davidbacisin/cwru-ros-pkg-hydro-beta#15]
Well, yes!  The simulator is ideal, whereas the robot is nonideal.  IRL you have to account for things like wheel slipping, noisey data, weight/momentum of the actual robot and a whole lot more!
Dr. Newman would be a better person to ask about the physics and stuff.  This would be a good question to bring up in class, in fact.

If you have any specific questions, I could probably help you out still.  If you wanna dig deeper, check out this folder of our repo: https://github.com/cwru-robotics/cwru-ros-pkg-hydro/tree/master/catkin/src/cwru_base_hydro/cwru_configs

And familiarize yourself with the ROS param sever: http://wiki.ros.org/Parameter%20Server

Have a good weekend!
Luc

**Comment by davidbacisin** [comment]
I suspect that the weight/momentum is the problem. It's a 200+ lb robot, and I assume it does not have brakes. I'm also guessing that it has some special brake to make it stop only when v = 0.

I'll check out the resources, but I don't know if I'll be able to make it to the lab today. I'll let you know if I can make it.

**Comment by Sandstome** [comment]
That's fine, we may just be better off waiting until class / office hours
Tuesday and talking with them to learn more about the braking features. The
only thing I can think to test before then would be our PS3 code and see if
the lidar stop works properly.

**Comment by davidbacisin** [comment]
Fixed! A lower max acceleration and the new safe-danger-critical zoning system for LIDAR seems to have fixed our problems.
