### ISSUE TITLE
E-stop status node

### ISSUE THREAD

**Issue by davidbacisin** [davidbacisin/cwru-ros-pkg-hydro-beta#3]
Listens to hardware
Publishes Boolean to "estop_status"

**Comment by Sandstome** [comment]
So looking at this, it looks like the hardware is already broadcasting the status of the E-Stop. His example looks like it uses all of 10 lines of code that we could probably just put into cmd_vel?

**Comment by davidbacisin** [comment]
Yeah, I agree we should just put this directly into vel_scheduler
